In [25]:
'''
Jiajun Li, A16635772
Academic Integrity Policy: Integrity of scholarship is essential for an academic
community. The University expects that both faculty and students will honor this
principle and in so doing protect the validity of University intellectual work. For
students, this means that all academic work will be done by the individual to
whom it is assigned, without unauthorized aid of any kind. By including this in
my report, I agree to abide by the Academic Integrity Policy.
'''


from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np
#Programming with Matrices
# i
# Create a matrix
A = np.array([[60,-15,12,22,68],
                   [-97, 28,91,-49,7],
                   [9,57,-91,91,-88],
                   [29,-92,42,38,99],
                   [-58,91,90,95,-62]])
B = np.array([[1,1,0,1,1],
                   [1, 0,1,1,0],
                   [1,0,0,1,0],
                   [1,1,0,0,1],
                   [0,0,1,0,0]])

In [4]:
# ii
for row in range(len(A)):
    for col in range(len(A[row])):
        if A[row][col] < -70:
            print("val",A[row][col],"in row",row+1,"and col",col+1)

val -97 in row 2 and col 1
val -91 in row 3 and col 3
val -88 in row 3 and col 5
val -92 in row 4 and col 2


In [13]:
# iii
C = np.multiply(A,B)
C

array([[ 60, -15,   0,  22,  68],
       [-97,   0,  91, -49,   0],
       [  9,   0,   0,  91,   0],
       [ 29, -92,   0,   0,  99],
       [  0,   0,  90,   0,   0]])

In [14]:
# iv
np.inner(C[:,2],C[4,:])

0

In [18]:
# v
C[:,3].max()
arr = C[:,3]
row_pos = np.where(arr == 91)[0][0]
print("val", C[:,3].max(), "in row", row_pos+1, "and col", 4)

91

val 91 in row 3 and col 4


In [32]:
# vi
row_first_C = C[0,:]
D = np.multiply(row_first_C,C)
D

array([ 60, -15,   0,  22,  68])

array([[ 3600,   225,     0,   484,  4624],
       [-5820,     0,     0, -1078,     0],
       [  540,     0,     0,  2002,     0],
       [ 1740,  1380,     0,     0,  6732],
       [    0,     0,     0,     0,     0]])

In [33]:
# vii
row_first_D = D[0,:]
E = np.multiply(row_first_D,D)
E

array([ 60, -15,   0,  22,  68])

array([[ 12960000,     50625,         0,    234256,  21381376],
       [-20952000,         0,         0,   -521752,         0],
       [  1944000,         0,         0,    968968,         0],
       [  6264000,    310500,         0,         0,  31128768],
       [        0,         0,         0,         0,         0]])

In [ ]:
# Robot Traversal
# i
# - The loc keeps track of the position of the robot.
# - The robot should moves one step to south.
# - If a object is detected in the south direction, 
#   the robot will move a step to west, since the loc 
#   of the robot is added by [0, -1] if object detected.
# - The robot would not be considered an intelligent system 
#   because 